//MEDICINE
export const INCREMENT_COUNTER="INCREMENT_COUNTER"
export const DECREMENT_COUNTER="DECREMENT_COUNTER"
export const GET_MEDICINE="GET_MEDICINE"
export const LOADING_MEDICINE="LOADING_MEDICINE"
export const ERROR_MEDICINE="ERROR_MEDICINE"
export const POST_MEDICINE="POST_MEDICINE"
export const DELETE_MEDICINE="DELETE_MEDICINE"
export const UPADATE_MEDICINE="UPADATE_MEDICINE"


//DOCTORE
export const GET_DOCTORE="GET_DOCTORE"
export const LOADING_DOCTORE="LOADING_DOCTORE"
export const ERROR_DOCTORE="ERROR_DOCTORE"
export const POST_DOCTORE="POST_DOCTORE"
export const DELETE_DOCTORE="DELETE_DOCTORE"
export const UPADATE_DOCTORE="UPADATE_DOCTORE"